{{- $portName := include "testapi.portName" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "testapi.fullname" . }}
  labels:
    {{- include "testapi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ $portName }}
      protocol: TCP
      name: {{ $portName }}
  selector:
    {{- include "testapi.selectorLabels" . | nindent 4 }}
